export type Region =
  | "Northland"
  | "Waikato"
  | "Auckland North"
  | "Auckland West"
  | "Auckland Central"
  | "Auckland East"
  | "Auckland South"
  | "Bay of Plenty"
  | "Taranaki"
  | "Whanganui"
  | "Manawatu"
  | "Marlborough"
  | "Wellington"
  | "Nelson"
  | "Tasman"
  | "Canterbury"
  | "Otago";

export interface IStoreDetails {
  name: string;
  lngLat: [number, number];
  address: string;
  locality: string;
  postcode: string;
  region: Region;
  phone?: string;
  storeBrand?: string;
  storeType: string;
  href: string;
}
export const stores: IStoreDetails[] = [
  {
    name: "Kerikeri Countdown",
    address: "Cnr Butler & Kerikeri Rds",
    locality: "Kerikeri",
    postcode: "0230",
    region: "Northland",
    phone: "(09) 407 0030",
    lngLat: [173.946844, -35.22932],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9502/kerikeri/kerikeri-countdown",
  },
  {
    name: "Whangarei Countdown",
    address: "Whangarei Retail Centre, Okara Drive",
    locality: "Whangarei",
    postcode: "0110",
    region: "Northland",
    phone: "(09) 430 4300",
    lngLat: [174.327329, -35.7305622],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9195/whangarei/whangarei-countdown",
  },
  {
    name: "Regent Countdown",
    address: "11 Kamo Road",
    locality: "Regent",
    postcode: "0112",
    region: "Northland",
    phone: "(09) 437 9019",
    lngLat: [174.322415, -35.714565],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9048/regent-whangarei/regent-countdown",
  },
  {
    name: "Whitianga Countdown",
    address: "24 Joan Gaskell Drive",
    locality: "Whitianga",
    postcode: "3510",
    region: "Waikato",
    phone: "(07) 867 2003",
    lngLat: [175.696961, -36.834515],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9049/whitianga/whitianga-countdown",
  },
  {
    name: "Warkworth Countdown",
    address: "Neville Street",
    locality: "Warkworth",
    postcode: "0910",
    region: "Auckland North",
    phone: "(09) 425 1117",
    lngLat: [174.6649729, -36.3988426],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9533/warkworth/warkworth-countdown",
  },
  {
    name: "Orewa Countdown",
    address: "Moenui Avenue",
    locality: "Orewa",
    postcode: "0931",
    region: "Auckland North",
    phone: "(09) 421 9300",
    lngLat: [174.6950692, -36.5886051],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9061/orewa/orewa-countdown",
  },
  {
    name: "Silverdale Countdown",
    address: "40 Hibiscus Coast Highway",
    locality: "Silverdale",
    postcode: "0932",
    region: "Auckland North",
    phone: "(09) 421 9185",
    lngLat: [174.6809176, -36.615197],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9504/silverdale/silverdale-countdown",
  },
  {
    name: "Whangaparaoa Countdown",
    address: "Cnr Whangaparaoa Road & Wade River Road",
    locality: "Whangaparaoa",
    postcode: "0932",
    region: "Auckland North",
    phone: "(09) 424 9222",
    lngLat: [174.7449325, -36.6353382],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9242/whangaparaoa/whangaparaoa-countdown",
  },
  {
    name: "Browns Bay Countdown",
    address: "Cnr Anzac & Clyde Roads",
    locality: "Browns Bay",
    postcode: "0630",
    region: "Auckland North",
    phone: "(09) 476 5974",
    lngLat: [174.7679642, -36.7883551],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9224/browns-bay/browns-bay-countdown",
  },
  {
    name: "Mairangi Bay Countdown",
    address: "3 Ramsgate Terrace",
    locality: "Mairangi Bay",
    postcode: "0630",
    region: "Auckland North",
    phone: "(09) 478 7402",
    lngLat: [174.75312, -36.73979],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9248/mairangi-bay/mairangi-bay-countdown",
  },
  {
    name: "Sunnynook Countdown",
    address: "Cnr Sycamore Drive & Sunnynook Road",
    locality: "Sunnynook",
    postcode: "0620",
    region: "Auckland North",
    phone: "(09) 410 8491",
    lngLat: [174.74113, -36.75909],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9197/sunnynook/sunnynook-countdown",
  },
  {
    name: "Milford Countdown",
    address: "Milford Shopping Centre, Milford Road",
    locality: "Milford",
    postcode: "0620",
    region: "Auckland North",
    phone: "(09) 486 0374",
    lngLat: [174.76499, -36.77182],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9198/milford/milford-countdown",
  },
  {
    name: "Glenfield Countdown",
    address: "Glenfield Mall, Bentley Avenue",
    locality: "Glenfield",
    postcode: "0629",
    region: "Auckland North",
    phone: "(09) 442 1041",
    lngLat: [174.72162, -36.77526],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9163/glenfield/glenfield-countdown",
  },
  {
    name: "Takapuna Countdown",
    address: "Barry's Point Road",
    locality: "Takapuna",
    postcode: "0622",
    region: "Auckland North",
    phone: "(09) 486 7538",
    lngLat: [174.76514, -36.79331],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9237/takapuna/takapuna-countdown",
  },
  {
    name: "Hauraki Countdown",
    address: "367 Lake Road",
    locality: "Hauraki",
    postcode: "0627",
    region: "Auckland North",
    phone: "(09) 486 3186",
    lngLat: [174.77809, -36.79672],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9060/belmont-hauraki/hauraki-corner-countdown",
  },
  {
    name: "Birkenhead Countdown",
    address: "Cnr Highbury Pass & Birkenhead Avenue",
    locality: "Birkenhead",
    postcode: "0626",
    region: "Auckland North",
    phone: "(09) 480 2921",
    lngLat: [174.72549, -36.81007],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9145/birkenhead/birkenhead-countdown",
  },
  {
    name: "Hobsonville Countdown",
    address: "124 Hobsonville Road",
    locality: "Hobsonville",
    postcode: "0616",
    region: "Auckland West",
    phone: "(09) 416 7516",
    lngLat: [174.64854, -36.79792],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9551/hobsonville/hobsonville-countdown",
  },
  {
    name: "Northwest Countdown",
    address: "7 Fred Taylor Drive, Northwest Town Centre",
    locality: "Westgate",
    postcode: "0814",
    region: "Auckland West",
    phone: "(09) 416 0934",
    lngLat: [174.61258, -36.8193],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9064/westgate-massey/northwest-countdown",
  },
  {
    name: "Westgate Countdown",
    address: "Northwest Town Centre",
    locality: "Massey North",
    postcode: "0614",
    region: "Auckland West",
    phone: "(09) 832 5382",
    lngLat: [174.91323, -36.93379],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9147/massey/westgate-countdown",
  },
  {
    name: "Te Atatu Countdown",
    address: "583 Te Atatu Road",
    locality: "Te Atatu",
    postcode: "0610",
    region: "Auckland West",
    phone: "(09) 834 5451",
    lngLat: [174.65175, -36.84271],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9451/te-atatu-peninsula/te-atatu-countdown",
  },
  {
    name: "Lincoln Road Countdown",
    address: "185 – 187 Universal Drive",
    locality: "Henderson",
    postcode: "0610",
    region: "Auckland West",
    phone: "(09) 835 3985",
    lngLat: [174.63115, -36.857],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9038/henderson/lincoln-road-countdown",
  },
  {
    name: "Henderson Countdown",
    address: "West City Shopping Centre, 7 Catherine Street",
    locality: "Henderson",
    postcode: "0612",
    region: "Auckland West",
    phone: "(09) 838 4953",
    lngLat: [174.63528, -36.86761],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9194/henderson/henderson-countdown",
  },
  {
    name: "Kelston Countdown",
    address: "Cnr Great North & West Coast Roads",
    locality: "Glen Eden",
    postcode: "0602",
    region: "Auckland West",
    phone: "(09) 818 4372",
    lngLat: [174.664, -36.90817],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9146/glen-eden/kelston-countdown",
  },
  {
    name: "Lynfield Countdown",
    address: "570 Hillsborough Road",
    locality: "Lynfield",
    postcode: "1041",
    region: "Auckland Central",
    phone: "(09) 626 0596",
    lngLat: [174.72266, -36.92452],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9140/lynfield/lynfield-countdown",
  },
  {
    name: "Lynnmall Countdown",
    address: "Lynnmall Shopping Centre, Great North Road",
    locality: "New Lynn",
    postcode: "1041",
    region: "Auckland Central",
    phone: "(09) 629 0392",
    lngLat: [174.67764, -36.90867],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9149/new-lynn/lynnmall-countdown",
  },
  {
    name: "Mt Roskill Countdown",
    address: "112 Stoddard Rd",
    locality: "Mt Roskill",
    postcode: "1041",
    region: "Auckland Central",
    phone: "(09) 826 0340",
    lngLat: [174.72701, -36.90383],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9034/mt-roskill-auckland/mount-roskill-countdown",
  },
  {
    name: "Pt Chevalier Countdown",
    address: "13 Point Chevalier Road",
    locality: "Point Chevalier",
    postcode: "1022",
    region: "Auckland Central",
    phone: "(09) 849 6395",
    lngLat: [174.71014, -36.86993],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9123/point-chevalier-auckland/pt-chevalier-countdown",
  },
  {
    name: "Grey Lynn Countdown",
    address: "271 Richmond Road",
    locality: "Grey Lynn",
    postcode: "1022",
    region: "Auckland Central",
    phone: "(09) 378 6313",
    lngLat: [174.73187, -36.85435],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9068/grey-lynn-auckland/grey-lynn-countdown",
  },
  {
    name: "Ponsonby Countdown",
    address: "4 Williamson Avenue",
    locality: "Ponsonby",
    postcode: "1021",
    region: "Auckland Central",
    phone: "(09) 376 5097",
    lngLat: [174.74898, -36.8586],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9057/ponsonby-auckland/ponsonby-countdown",
  },
  {
    name: "Grey Lynn Central Countdown",
    address: "Cnr Coleridge & Williamson Avenues",
    locality: "Grey Lynn",
    postcode: "1021",
    region: "Auckland Central",
    phone: "(09) 360 4287",
    lngLat: [174.73836, -36.86463],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9068/grey-lynn-auckland/grey-lynn-countdown",
  },
  {
    name: "St Lukes Countdown",
    address: "80 St Lukes Road, St Lukes Shopping Centre",
    locality: "Mount Albert",
    postcode: "1025",
    region: "Auckland Central",
    phone: "(09) 846 9742",
    lngLat: [174.733, -36.88366],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9216/mt-albert-auckland/st-lukes-countdown",
  },
  {
    name: "Mt Eden Countdown",
    address: "Cnr Valley & Dominion Roads",
    locality: "Mt Eden",
    postcode: "1024",
    region: "Auckland Central",
    phone: "(09) 638 7164",
    lngLat: [174.75104, -36.87598],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9235/mt-eden-auckland/mount-eden-countdown",
  },
  {
    name: "Auckland City Countdown",
    address: "76 Quay Street",
    locality: "Auckland City",
    postcode: "1010",
    region: "Auckland Central",
    phone: "(09) 373 5017",
    lngLat: [174.77288, -36.84502],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9094/auckland/auckland-city-countdown",
  },
  {
    name: "Victoria Street West Countdown",
    address: "19-25 Victoria Street",
    locality: "Auckland City",
    postcode: "1010",
    region: "Auckland Central",
    phone: "(09) 308 9249",
    lngLat: [174.76302, -36.84857],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9283/auckland/auckland-victoria-street-west",
  },
  {
    name: "Waiheke Countdown",
    address: "13-19 Belgium Street, Ostend",
    locality: "Waiheke",
    postcode: "1021",
    region: "Auckland Central",
    phone: "(09) 372 8431",
    lngLat: [175.04539, -36.79586],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9030/ostend/waiheke-island-countdown",
  },
  {
    name: "Three Kings Countdown",
    address: "532 Mt Albert Road",
    locality: "Three Kings",
    postcode: "1042",
    region: "Auckland Central",
    phone: "(09) 624 2317",
    lngLat: [174.7554, -36.90884],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9529/three-kings-auckland/three-kings-countdown",
  },
  {
    name: "Greenlane Countdown",
    address: "326 Great South Road",
    locality: "Greenlane",
    postcode: "1051",
    region: "Auckland East",
    phone: "(09) 522 6970",
    lngLat: [174.79345, -36.8897],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9128/greenlane-auckland/greenlane-countdown",
  },
  {
    name: "Mt Wellington Countdown",
    address: "Cnr Penrose Road & Mt Wellington Highway",
    locality: "Mt Wellington",
    postcode: "1060",
    region: "Auckland East",
    phone: "(09) 527 8916",
    lngLat: [174.8388, -36.90852],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9193/mt-wellington/mount-wellington-countdown",
  },
  {
    name: "Meadowbank Countdown",
    address: "35-47 St Johns Road",
    locality: "Meadowbank",
    postcode: "1072",
    region: "Auckland East",
    phone: "(09) 578 0540",
    lngLat: [174.82774, -36.87576],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9444/meadowbank/meadowbank-countdown",
  },
  {
    name: "St Johns Countdown",
    address: "134 - 144 Felton Mathew Avenue",
    locality: "St Johns",
    postcode: "1072",
    region: "Auckland East",
    phone: "(09) 578 3546",
    lngLat: [174.85174, -36.87929],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9521/st-johns/st-johns-countdown",
  },
  {
    name: "Aviemore Park Countdown",
    address: "Highland Park Shopping Centre, Pakuranga Highway",
    locality: "Highland Park",
    postcode: "2010",
    region: "Auckland East",
    phone: "(09) 537 6584",
    lngLat: [174.91392, -36.90354],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9215/pakuranga/aviemore-drive-countdown",
  },
  {
    name: "Howick Countdown",
    address: "35 Cook Street",
    locality: "Howick",
    postcode: "2014",
    region: "Auckland East",
    phone: "(09) 535 9738",
    lngLat: [174.93338, -36.89637],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9243/howick/howick-countdown",
  },
  {
    name: "Botany Downs Countdown",
    address: "Cnr Te Irirangi Drive & Ti Rakau Drive",
    locality: "Botany",
    postcode: "2010",
    region: "Auckland East",
    phone: "(09) 271 3634",
    lngLat: [174.8737, -36.91769],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9141/botany-downs/botany-downs-countdown",
  },

  {
    name: "Meadowlands Countdown",
    address: "Cnr Meadowlands Drive & Whitford Road",
    locality: "Howick",
    postcode: "2014",
    region: "Auckland East",
    phone: "(09) 537 8497",
    lngLat: [174.92839, -36.91599],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9458/howick/meadowlands-countdown",
  },
  {
    name: "Beachlands Countdown",
    address: "129 Beachlands Road",
    locality: "Beachlands",
    postcode: "2018",
    region: "Auckland East",
    phone: "(09) 536 5176",
    lngLat: [175.01085, -36.88961],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9177/beachlands/beachlands-countdown",
  },
  {
    name: "Manukau Countdown",
    address: "652 Great South Road",
    locality: "Manukau",
    postcode: "2104",
    region: "Auckland South",
    phone: "(09) 263 9765",
    lngLat: [174.88229, -36.98755],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9161/manukau/manukau-countdown",
  },
  {
    name: "Takanini Countdown",
    address: "228 Great South Road",
    locality: "Takanini",
    postcode: "2112",
    region: "Auckland South",
    phone: "(09) 298 6573",
    lngLat: [174.9274, -37.04856],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9202/takanini/takanini-countdown",
  },
  {
    name: "Pukekohe Countdown",
    address: "Cnr Tobin & Seddon Streets",
    locality: "Pukekohe",
    postcode: "2120",
    region: "Auckland South",
    phone: "(09) 237 0220",
    lngLat: [174.90245, -37.19995],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9199/pukekohe/pukekohe-countdown",
  },
  {
    name: "Pukekohe South Countdown",
    address: "186-192 Manukau Road",
    locality: "Pukekohe",
    postcode: "2120",
    region: "Auckland South",
    phone: "(09) 237 3080",
    lngLat: [174.91065, -37.2112],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9107/pukekohe/pukekohe-south-countdown",
  },
  {
    name: "St James Countdown",
    address: "Cnr Hukanui & Thomas Roads",
    locality: "Rototuna",
    postcode: "3210",
    region: "Waikato",
    phone: "(07) 853 0017",
    lngLat: [175.26635, -37.73058],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9103/rototuna-hamilton/st-james-countdown",
  },
  {
    name: "Te Rapa Countdown",
    address: "8 Eagle Way",
    locality: "Te Rapa",
    postcode: "3200",
    region: "Waikato",
    phone: "(07) 850 5091",
    lngLat: [175.23383, -37.74648],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9282/te-rapa-hamilton/te-rapa-countdown",
  },
  {
    name: "Hamilton Countdown",
    address: "Cnr Anglesea & Liverpool Streets",
    locality: "Hamilton Central",
    postcode: "3204",
    region: "Waikato",
    phone: "(07) 834 1490",
    lngLat: [175.27368, -37.78112],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9192/hamilton/hamilton-countdown",
  },
  {
    name: "Hamilton Bridge Countdown",
    address: "Cnr Bridge & Anglesea Street",
    locality: "Hamilton Central",
    postcode: "3204",
    region: "Waikato",
    phone: "(07) 838 2714",
    lngLat: [175.2828, -37.7908],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9033/hamilton/bridge-street-countdown?lat=-37.77461872239307&long=175.265665401189&q=",
  },
  {
    name: "Claudelands Countdown",
    address: "160 Peachgrove Road",
    locality: "Hamilton East",
    postcode: "3216",
    region: "Waikato",
    phone: "(07) 853 0003",
    lngLat: [175.29896, -37.77835],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9473/hamilton-east/claudelands-countdown",
  },
  {
    name: "Cambridge Countdown",
    address: "Cnr Queen & Empire Streets",
    locality: "Cambridge",
    postcode: "3434",
    region: "Waikato",
    phone: "(07) 823 5971",
    lngLat: [175.46983, -37.89151],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9153/cambridge/cambridge-countdown",
  },
  {
    name: "Te Awamutu Countdown",
    address: "181 Sloane Street",
    locality: "Te Awamutu",
    postcode: "3800",
    region: "Waikato",
    phone: "(07) 8720740",
    lngLat: [175.32677, -38.01194],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9449/te-awamutu/te-awamutu-countdown",
  },
  {
    name: "Katikati Countdown",
    address: "123-131 Main Road",
    locality: "Katikati",
    postcode: "3129",
    region: "Waikato",
    phone: "(07) 549 4603",
    lngLat: [175.91594, -37.55967],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9453/katikati/katikati-countdown",
  },
  {
    name: "Bureta Park Countdown",
    address: "44-50 Bureta Road",
    locality: "Otumoetai",
    postcode: "3110",
    region: "Bay of Plenty",
    phone: "(07) 576 1727",
    lngLat: [176.15354, -37.6684],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9050/tauranga/bureta-park-countdown",
  },
  {
    name: "Tauranga Countdown",
    address: "618 Cameron Road",
    locality: "Tauranga",
    postcode: "3112",
    region: "Bay of Plenty",
    phone: "(07) 578 0055",
    lngLat: [176.15773, -37.70041],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9162/tauranga/tauranga-countdown",
  },
  {
    name: "Bethlehem Countdown",
    address: "19 Bethlehem Road",
    locality: "Bethlehem",
    postcode: "3110",
    region: "Bay of Plenty",
    phone: "(07) 579 2862",
    lngLat: [176.1098, -37.69299],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9143/tauranga/bethlehem-countdown",
  },
  {
    name: "Bayfair Countdown",
    address: "Bayfair Shopping Centre, 1-19 Girven Road",
    locality: "Mt Maunganui",
    postcode: "3116",
    region: "Bay of Plenty",
    phone: "(07) 547 4560",
    lngLat: [176.21359, -37.67975],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9415/mt-maunganui-tauranga/bayfair-countdown",
  },
  {
    name: "Fraser Cove Countdown",
    address: "229-233 Fraser Street, Fraser Cove Shopping Centre",
    locality: "Parkvale",
    postcode: "3112",
    region: "Bay of Plenty",
    phone: "(07) 571 0500",
    lngLat: [176.15126, -37.71108],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9113/tauranga/fraser-cove-countdown",
  },
  {
    name: "Papamoa Countdown",
    address: "Papamoa Shopping Centre, Domain Road",
    locality: "Royal Palm Beach",
    postcode: "3118",
    region: "Bay of Plenty",
    phone: "(07) 547 4024",
    lngLat: [176.28109, -37.6992307],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9472/papamoa/papamoa-countdown",
  },
  {
    name: "Rotorua Countdown",
    address: "246 Fenton Street",
    locality: "Rotorua",
    postcode: "3010",
    region: "Bay of Plenty",
    phone: "(07) 350 3277",
    lngLat: [176.25412, -38.14337],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9189/rotorua/rotorua-countdown",
  },
  {
    name: "Countdown Central Mall",
    address: "Rotorua Central Mall, Victoria Street",
    locality: "Rotorua",
    postcode: "3010",
    region: "Bay of Plenty",
    phone: "(07) 349 6501",
    lngLat: [176.25135, -38.13686],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9110/rotorua/central-mall-countdown",
  },
  {
    name: "Fairy Springs Countdown",
    address: "54 Fairy Springs Road",
    locality: "Fairy Springs",
    postcode: "3015",
    region: "Bay of Plenty",
    phone: "(07) 343 6070",
    lngLat: [176.22832, -38.1201],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9173/rotorua/fairy-springs-countdown",
  },
  {
    name: "Whakatane Countdown",
    address: "105-125 Commerce Street",
    locality: "Whakatane",
    postcode: "3120",
    region: "Bay of Plenty",
    phone: "(07) 306 0014",
    lngLat: [176.99505, -37.95612],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9170/whakatane/whakatane-countdown",
  },
  {
    name: "Napier Countdown",
    address: "Cnr Munroe & Dickens Streets",
    locality: "Napier",
    postcode: "4110",
    region: "Bay of Plenty",
    phone: "(06) 834 1401",
    lngLat: [176.91535, -39.492],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9130/napier/carlyle-countdown",
  },
  {
    name: "Carlyle Countdown",
    address: "Carlyle Street",
    locality: "Napier",
    postcode: "4110",
    region: "Bay of Plenty",
    phone: "(06) 835 3643",
    lngLat: [176.90672, -39.4932],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "",
  },
  {
    name: "The Valley Countdown",
    address: "The Valley Mega Centre, 1 Vickers Road",
    locality: "Waiwhakaiho",
    postcode: "4312",
    region: "Taranaki",
    phone: "(06) 757 3330",
    lngLat: [174.11707, -39.0429],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9133/waiwhakaiho-new-plymouth/the-valley-countdown",
  },
  {
    name: "New Plymouth Central Countdown",
    address: "174 Courtenay Street",
    locality: "New Plymouth",
    postcode: "4310",
    region: "Taranaki",
    phone: "(06) 759 7481",
    lngLat: [174.08237, -39.05645],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9528/new-plymouth/new-plymouth-central-countdown",
  },
  {
    name: "Spotswood Countdown",
    address: "Cnr Manadon St & South Rd",
    locality: "Spotswood",
    postcode: "4310",
    region: "Taranaki",
    phone: "(06) 751 0485",
    lngLat: [174.03399, -39.07588],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9425/new-plymouth/spotswood-countdown",
  },
  {
    name: "Hawera Countdown",
    address: "39 Nelson Street",
    locality: "Hawera",
    postcode: "4610",
    region: "Taranaki",
    phone: "(06) 278 0026",
    lngLat: [174.2812, -39.58744],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9431/hawera/hawera-countdown",
  },
  {
    name: "Whanganui Countdown",
    address: "Trafalgar Square, Cnr Taupo Quay & Wilson Street",
    locality: "Whanganui",
    postcode: "4500",
    region: "Whanganui",
    phone: "(06) 349 0199",
    lngLat: [175.05204, -39.9357],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9151/wanganui/wanganui-countdown?lat=-39.9334197333&long=175.0571094&q=%20near%2011%20Taupo%20Quay,%20Whanganui%204500",
  },
  {
    name: "Victoria Ave Countdown",
    address: "433 Victoria Avenue",
    locality: "Whanganui",
    postcode: "4500",
    region: "Whanganui",
    phone: "(06) 349 0070",
    lngLat: [175.03884, -39.92532],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9129/wanganui/victoria-ave-countdown",
  },
  {
    name: "Palmerston North Countdown",
    address: "Cnr Ferguson & Ashley Streets",
    locality: "Palmerston North",
    postcode: "4410",
    region: "Manawatu",
    phone: "(06) 356 6066",
    lngLat: [175.61621, -40.35823],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9155/palmerston-north/palmerston-north-countdown",
  },
  {
    name: "Kelvin Grove Countdown",
    address: "7 Fernlea Avenue",
    locality: "Kelvin Grove",
    postcode: "4470",
    region: "Manawatu",
    phone: "(06) 356 6067",
    lngLat: [175.65301, -40.33007],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9424/kelvin-grove-palmerston-north/kelvin-grove-countdown",
  },
  {
    name: "Upper Hutt Countdown",
    address: "13-19 Queen Street",
    locality: "Upper Hutt",
    postcode: "5018",
    region: "Wellington",
    phone: "(04) 527 2003",
    lngLat: [175.07069, -41.12308],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9157/upper-hutt/upper-hutt-countdown",
  },
  {
    name: "Lower Hutt Countdown",
    address: "261 High Street",
    locality: "Lower Hutt",
    postcode: "5010",
    region: "Wellington",
    phone: "(04) 576 2000",
    lngLat: [174.90535, -41.20785],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9156/lower-hutt/lower-hutt-countdown",
  },
  {
    name: "Queensgate Countdown",
    address: "Queensgate Shopping Centre, 35 Bloomfield Terrace",
    locality: "Lower Hutt",
    postcode: "5010",
    region: "Wellington",
    phone: "(04) 569 3993",
    lngLat: [174.90282, -41.2116],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9489/lower-hutt/queensgate-countdown",
  },
  {
    name: "Petone Countdown",
    address: "45 Jackson Street",
    locality: "Petone",
    postcode: "5012",
    region: "Wellington",
    phone: "(04) 589 9573",
    lngLat: [174.87199, -41.22328],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9535/petone/petone-countdown",
  },
  {
    name: "Cable Car Lane Countdown",
    address: "280-284 Lambton Quay",
    locality: "Wellington City",
    postcode: "6011",
    region: "Wellington",
    phone: "(04) 499 3466",
    lngLat: [174.77521, -41.28421],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9066/wellington/cable-car-lane-countdown",
  },
  {
    name: "Karori Countdown",
    address: "Main Road",
    locality: "Karori",
    postcode: "6012",
    region: "Wellington",
    phone: "(04) 464 3000",
    lngLat: [174.82492, -41.29756],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9530/karori/karori-countdown",
  },
  {
    name: "Johnsonville Countdown",
    address: "Johnsonville Mall, Moorefield Road",
    locality: "Johnsonville",
    postcode: "6037",
    region: "Wellington",
    phone: "(04) 465 0990",
    lngLat: [174.80734, -41.22419],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9158/johnsonville/johnsonville-mall-countdown",
  },
  {
    name: "Crofton Downs Countdown",
    address: "Churchill Drive",
    locality: "Crofton Downs",
    postcode: "6035",
    region: "Wellington",
    phone: "(04) 479 2133",
    lngLat: [174.76654, -41.25903],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9031/crofton-downs/crofton-downs-countdown",
  },
  {
    name: "Tawa Countdown",
    address: "5 William Earp Place",
    locality: "Tawa",
    postcode: "5028",
    region: "Wellington",
    phone: "(04) 232 7057",
    lngLat: [174.83002, -41.18667],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9475/tawa/tawa-countdown",
  },
  {
    name: "Kilbirnie Countdown",
    address: "47 Bay Road",
    locality: "Kilbirnie",
    postcode: "6022",
    region: "Wellington",
    phone: "(04) 387 2049",
    lngLat: [174.7947, -41.31949],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9474/kilbirnie/kilbirnie-countdown",
  },
  {
    name: "Newtown Countdown",
    address: "3 John Street",
    postcode: "6021",
    locality: "Newtown",
    region: "Wellington",
    phone: "(04) 380 2080",
    lngLat: [174.77744, -41.30737],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9508/newtown/newtown-countdown",
  },
  {
    name: "Blenheim Countdown",
    address: "51 Arthur Street",
    locality: "Blenheim",
    postcode: "7201",
    region: "Marlborough",
    phone: "(03) 520 6130",
    lngLat: [173.953, -41.51174],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9160/blenheim/blenheim-countdown",
  },
  {
    name: "Redwoodtown Countdown",
    address: "Cnr Weld & Alabama Street",
    postcode: "7201",
    locality: "Redwoodtown",
    region: "Marlborough",
    phone: "(03) 520 6770",
    lngLat: [173.95464, -41.52825],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9212/blenheim/redwoodtown-countdown",
  },
  {
    name: "Nelson Countdown",
    address: "35 St Vincent Street",
    locality: "Nelson",
    postcode: "7010",
    region: "Nelson",
    phone: "(03) 546 7443",
    lngLat: [173.2345469, -41.3118968],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9159/nelson/nelson-countdown",
  },
  {
    name: "Stoke Countdown",
    address: "Cnr Putaitai Street & Main Road",
    locality: "Stoke",
    postcode: "7011",
    region: "Nelson",
    phone: "(03) 547 9298",
    lngLat: [173.2348982, -41.3119734],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9168/stoke/stoke-countdown",
  },
  {
    name: "Motueka Countdown",
    address: "108 High Street",
    locality: "Motueka",
    postcode: "7120",
    region: "Tasman",
    phone: "(03) 528 1170",
    lngLat: [173.0107716, -41.1095987],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9495/motueka/motueka-countdown",
  },
  {
    name: "Amberley Countdown",
    address: "Brackenfields Retail Centre, 129 Carters Road",
    locality: "Amberley",
    postcode: "7410",
    region: "Canterbury",
    phone: "(03) 314 0000",
    lngLat: [172.7321431, -43.156362],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9518/amberley/amberley-countdown",
  },
  {
    name: "Rangiora East Countdown",
    address: "40-54 Ivory Street",
    locality: "Rangiora",
    postcode: "7400",
    region: "Canterbury",
    phone: "(03) 311 8170",
    lngLat: [172.5988527, -43.3073469],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9284/rangiora-christchurch/rangiora-east-countdown",
  },
  {
    name: "Christchurch Airport Countdown",
    address: "530 - 546A Memorial Avenue",
    locality: "Christchurch Airport",
    postcode: "8053",
    region: "Canterbury",
    phone: "(03) 357 0450",
    lngLat: [172.547678, -43.489914],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9090/christchurch/christchurch-airport-countdown",
  },

  {
    name: "Northwood Countdown",
    address: "1 Radcliffe Road, Northwood Supa Centre",
    locality: "Belfast",
    postcode: "8051",
    region: "Canterbury",
    phone: "(03) 375 9024",
    lngLat: [172.625558, -43.459107],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9196/christchurch/northwood-countdown",
  },
  {
    name: "Northlands Countdown",
    address: "Cnr Main North Rd & Sawyers Arms Rd",
    locality: "Papanui",
    postcode: "8052",
    region: "Canterbury",
    phone: "(03) 375 0092",
    lngLat: [172.6117157, -43.4914625],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9174/papanuai-christchurch/northlands-countdown",
  },
  {
    name: "Church Cnr Countdown",
    address: "Cnr Riccarton Road & Hansons Lane",
    locality: "Riccarton",
    postcode: "8041",
    region: "Canterbury",
    phone: "(03) 348 3754",
    lngLat: [172.573094, -43.532603],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9176/riccarton-christchurch/church-cnr-countdown",
  },
  {
    name: "The Palms Countdown",
    address: "The Palms Plaza, Marshland Road",
    locality: "Shirley",
    postcode: "8061",
    region: "Canterbury",
    phone: "(03) 375 7003",
    lngLat: [172.6645278, -43.5056571],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9100/shirley/the-palms-countdown",
  },
  {
    name: "Hornby Countdown",
    address: "17 Chappie Place",
    locality: "Hornby",
    postcode: "8042",
    region: "Canterbury",
    phone: "(03) 344 0570",
    lngLat: [172.5269929, -43.5428131],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9121/hornby-christchurch/hornby-countdown",
  },
  {
    name: "Rollerston Countdown",
    address: "Cnr McCauley Street & Rolleston Drive",
    locality: "Rolleston",
    postcode: "7614",
    region: "Canterbury",
    phone: "(03) 347 8264",
    lngLat: [172.3866642, -43.59415],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9131/rolleston-christchurch/rolleston-countdown",
  },
  {
    name: "Colombo St Countdown",
    address: "219 Colombo Street",
    locality: "Sydenham",
    postcode: "8023",
    region: "Canterbury",
    phone: "(03) 337 5781",
    lngLat: [172.6355851, -43.55335215],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9180/christchurch/colombo-st-countdown",
  },
  {
    name: "Ferrymead Countdown",
    address: "999 Ferry Road",
    locality: "Ferrymead",
    postcode: "8023",
    region: "Canterbury",
    phone: "(03) 373 6520",
    lngLat: [172.702296, -43.556556],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9292/ferrymead-christchurch/ferrymead-countdown",
  },
  {
    name: "Timaru Countdown",
    address: "9 Browne Street",
    locality: "Parkside",
    postcode: "7910",
    region: "Canterbury",
    phone: "(03) 687 1229",
    lngLat: [171.2545953, -44.4022964],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9183/timaru/timaru-countdown",
  },
  {
    name: "Oamaru Countdown",
    address: "108-116 Thames Street",
    locality: "Oamaru",
    postcode: "9400",
    region: "Otago",
    phone: "(03) 433 0419",
    lngLat: [170.9705023, -45.0972152],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9182/oamaru/oamaru-countdown",
  },
  {
    name: "Queenstown Countdown",
    address: "30 Grant Road",
    locality: "Frankton",
    postcode: "9300",
    region: "Otago",
    phone: "(03) 441 0030",
    lngLat: [168.7414647, -45.013875],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9058/frankton-queenstown/queenstown-countdown",
  },
  {
    name: "Dunedin Central Countdown",
    address: "309 Cumberland Street",
    locality: "Dunedin Central",
    postcode: "9016",
    region: "Otago",
    phone: "(03) 477 7283",
    lngLat: [170.5063954, -45.8741213],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9190/dunedin/dunedin-central-countdown?lat=-45.87751965&long=170.5001039667&q=%20near%208%20Broadway,%20Dunedin%20Central,%20Dunedin%209016",
  },
  {
    name: "Dunedin South Countdown",
    address: "323 Andersons Bay Road",
    locality: "Dunedin South",
    postcode: "9012",
    region: "Otago",
    phone: "(03) 466 3100",
    lngLat: [170.5019883, -45.8927274],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9524/dunedin/dunedin-south-countdown?lat=-45.89452745&long=170.4962581667&q=%20near%208%20Reid%20Road,%20South%20Dunedin,%20Dunedin%209012",
  },
  {
    name: "Andersons Bay Countdown",
    address: "560 Andersons Bay Road",
    locality: "Dunedin South",
    postcode: "9012",
    region: "Otago",
    phone: "(03) 466 3225",
    lngLat: [170.5089154, -45.8964121],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9442/dunedin/andersons-bay-countdown?lat=-45.89640575&long=170.5254672833&q=%20near%201%20Bayfield%20Road,%20Andersons%20Bay,%20Dunedin%209013",
  },
  {
    name: "Mosgiel Countdown",
    address: "55 Gordon Road",
    locality: "Mosgiel",
    postcode: "9024",
    region: "Otago",
    phone: "(03) 489 0041",
    lngLat: [170.3523654, -45.8804003],
    storeBrand: "Countdown",
    storeType: "Supermarkets",
    href: "https://shop.countdown.co.nz/store-finder/9118/mosgiel-dunedin/mosgiel-countdown?lat=-45.8582993&long=170.3236126&q=%20near%20138%20Outram-Mosgiel%20Road,%20Mosgiel%209073",
  },
  {
    name: "Fire Dragon Chillies",
    address: "1087 Wekaweka Road, RD 3",
    locality: "Kaikohe",
    postcode: "0473",
    region: "Northland",
    phone: "(09) 4058439",
    lngLat: [173.581233, -35.56876],
    storeType: "Other Stockists",
    href: "https://www.firedragonchillies.co.nz/",
  },
  {
    name: "Orewa New World",
    address: "11 Moana Avenue",
    locality: "Orewa",
    postcode: "0931",
    region: "Auckland North",
    phone: "(09) 427 0117",
    lngLat: [174.6936005, -36.5864805],
    storeType: "Supermarkets",
    href: "https://www.newworld.co.nz/upper-north-island/auckland/orewa",
  },
  {
    name: "Frankies Gelato and Deli",
    address: "60 Rawhiti Road",
    locality: "Manly",
    postcode: "0930",
    region: "Auckland North",
    phone: "(09) 600 8058",
    lngLat: [174.762693, -36.631258],
    storeType: "Other Stockists",
    href: "https://www.facebook.com/frankiesgelatodeli/",
  },
  {
    name: "The Village Butcher",
    address: "359 Lake Road",
    locality: "Hauraki",
    postcode: "0622",
    region: "Auckland North",
    phone: "(09) 4898364",
    lngLat: [174.7782366, -36.7968242],
    storeType: "Other Stockists",
    href: "https://www.facebook.com/thevillagebutchernz/",
  },
  {
    name: "Fresh Collective",
    address: "1A Alberton Avenue",
    locality: "Mt Albert",
    postcode: "1025",
    region: "Auckland Central",
    phone: "(09) 8494 2311",
    lngLat: [174.7260345, -36.8802662],
    storeType: "Other Stockists",
    href: "https://www.newworld.co.nz/upper-north-island/auckland/fresh-collective-alberton",
  },
  {
    name: "Chantal's",
    address: "45 Hastings Street",
    locality: "Napier South",
    postcode: "4110",
    region: "Bay of Plenty",
    phone: "(06) 8358036",
    lngLat: [176.9176507, -39.489251],
    storeType: "Other Stockists",
    href: "https://www.chantalshop.nz/",
  },
  {
    name: "Bin Inn Paraparaumu",
    address: "128 Kapiti Road",
    locality: "Paraparaumu",
    postcode: "5032",
    region: "Wellington",
    phone: "(04) 2989384",
    lngLat: [174.997599, -40.905639],
    storeType: "Other Stockists",
    href: "https://www.bininn.co.nz/wellington",
  },
  {
    name: "Waikanae Butcher",
    address: "42 Main Road",
    locality: "Waikanae",
    postcode: "5036",
    region: "Wellington",
    phone: "(04) 9026776",
    lngLat: [175.0646744, -40.87755875],
    storeType: "Other Stockists",
    href: "https://waikanaebutchery.co.nz/",
  },
  {
    name: "Moore Wilsons Porirua",
    address: "65 Kenepuru Drive",
    locality: "Porirua",
    postcode: "5022",
    region: "Wellington",
    phone: "(04) 237 8320",
    lngLat: [174.837137, -41.148853],
    storeBrand: "Moore Wilsons",
    storeType: "Supermarkets",
    href: "https://moorewilsons.co.nz/porirua",
  },
  {
    name: "Miramar New World",
    address: "48 Miramar Avenue",
    locality: "Miramar",
    postcode: "6022",
    region: "Wellington",
    phone: "(04) 388 2934",
    lngLat: [174.8141957, -41.3161765],
    storeBrand: "New World",
    storeType: "Supermarkets",
    href: "https://www.newworld.co.nz/lower-north-island/wellington/miramar/",
  },
  {
    name: "Buster's Pizza",
    address: "68 Kingsford Smith Street",
    locality: "Rongotai",
    postcode: "6022",
    region: "Wellington",
    phone: "(04) 3871155",
    lngLat: [174.800173, -41.327415],
    storeType: "Other Stockists",
    href: "https://busters-woodfired-pizza.business.site/",
  },
  {
    name: "Coolsville Cartel",
    address: "3c Moxham Avenue",
    locality: "Hataitai",
    postcode: "6021",
    region: "Wellington",
    phone: "(04) 386 4513",
    lngLat: [174.794165, -41.304315],
    storeType: "Other Stockists",
    href: "https://www.coolsvillecartel.com/",
  },
  {
    name: "Trading Post",
    address: "35 Waitoa Road",
    locality: "Hataitai",
    postcode: "6021",
    region: "Wellington",
    phone: "(021) 0866 1434",
    lngLat: [174.793654, -41.304049],
    storeType: "Other Stockists",
    href: "/",
  },
  {
    name: "Moore Wilsons",
    address: "Corner of Tory Street & College Street",
    locality: "Te Aro",
    postcode: "6011",
    region: "Wellington",
    phone: "(04) 384 9906",
    lngLat: [174.7806878, -41.29574675],
    storeBrand: "Moore Wilsons",
    storeType: "Supermarkets",
    href: "https://moorewilsons.co.nz/",
  },
  {
    name: "Thorndon New World",
    address: "150 Molesworth Street",
    locality: "Thorndon",
    postcode: "6011",
    region: "Wellington",
    phone: "(04) 499 9041",
    lngLat: [174.7784177, -41.27411255],
    storeBrand: "New World",
    storeType: "Supermarkets",
    href: "https://www.newworld.co.nz/lower-north-island/wellington/thorndon/",
  },
  {
    name: "Wellington Gilmours",
    address: "33 Bouverie Street",
    locality: "Petone",
    postcode: "5012",
    region: "Wellington",
    phone: "(04) 499 5130",
    lngLat: [174.8810746, -41.218885],
    storeBrand: "Gilmours",
    storeType: "Wholesalers",
    href: "https://www.gilmours.co.nz/locations/wellington/",
  },
  {
    name: "Mt Roskill Gilmours",
    address: "103-105 May Road",
    locality: "Mount Roskill",
    postcode: "1041",
    region: "Auckland West",
    phone: "0800 270 414",
    lngLat: [174.7304946, -36.9108065],
    storeBrand: "Gilmours",
    storeType: "Wholesalers",
    href: "https://www.gilmours.co.nz/locations/mt-roskill/",
  },
];

export interface IMapRange {
  label: string;
  meters: number;
}

export const RANGES: IMapRange[] = [
  {
    label: "5km",
    meters: 5000,
  },
  {
    label: "25km",
    meters: 25000,
  },
  {
    label: "100km",
    meters: 100000,
  },
];
